languageCode = "en"
languageName = "English"
weight = 1
title = "Kenneth Ong"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"

[author]
name = "Kenneth Ong"
image = "avatar.jpg"
headline = "Dream big and dare to fail"
bio = "A little bit about you"
links = [ { email = "kennethongkp@gmail.com" }, { github = "https://github.com/KennethOng02" }, { linkedin = "https://www.linkedin.com/in/kenneth-kuan-phing-ong-5b31322b8/" } ]
